# Generated by Django 5.1.1 on 2024-10-29 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado_notas', models.TextField()),
                ('acta_culminacion', models.TextField()),
                ('plan_estudios', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_otorgado', models.CharField(max_length=100)),
                ('certificacion_titulo', models.TextField()),
                ('publicacion_gaceta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_usuario', models.CharField(choices=[('alumno', 'Alumno'), ('docente', 'Docente'), ('administrador', 'Administrador')], max_length=50)),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CursoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.curso')),
            ],
            options={
                'unique_together': {('curso', 'alumno')},
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='cursos',
            field=models.ManyToManyField(through='App.CursoAlumno', to='App.curso'),
        ),
        migrations.CreateModel(
            name='CursoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursos', models.ManyToManyField(through='App.CursoDocente', to='App.curso')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='cursodocente',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.docente'),
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.alumno')),
                ('certificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.certificacion')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.titulo')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_por_cuatrimestre', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cuatrimestre', models.CharField(max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.alumno')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.expediente')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='cursodocente',
            unique_together={('curso', 'docente')},
        ),
    ]
