# Generated by Django 4.2.16 on 2024-11-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='docente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'docente',
                'managed': False,
            },
        ),
    ]
