# Generated by Django 5.1.2 on 2024-10-29 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='alumno',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'tipo_usuario': 'alumno'}, on_delete=django.db.models.deletion.CASCADE, to='App.usuario'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'tipo_usuario': 'docente'}, on_delete=django.db.models.deletion.CASCADE, to='App.usuario'),
        ),
    ]
