# Generated by Django 4.2.16 on 2024-11-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alumnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_encabezado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'plan_encabezado',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Alumnos',
        ),
    ]
