# Generated by Django 5.1.2 on 2024-10-29 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_nota_alumno_alter_alumno_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.alumno'),
        ),
    ]
