# Generated by Django 5.1.2 on 2024-10-29 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_nota_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.alumno'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='titulo_otorgado',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
