# Generated by Django 5.1.2 on 2024-10-29 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_curso_nombre_alter_nota_alumno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.alumno'),
        ),
    ]
